In [69]:
#imports the pandas library
import pandas as pd

In [72]:
#reads in the .csv file
stock_financials = pd.read_csv("S&P 500 - Financials - July 2020.csv")

#reads in the .csv file
#the encoding portion of the code is required - without it, a unicode decode error is produced (found the solution on Stack Overflow)
stock_info = pd.read_csv("sp500-companies.csv",encoding='windows-1252')

In [73]:
#This code will give us a snapshot of the data in the financial file
stock_financials.head()

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,1.387211e+11,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,1.078342e+10,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,1.021210e+11,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,1.813863e+11,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,9.876586e+10,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [74]:
#This code will give us a snapshot of the data in the information file
stock_info.head()

,Ticker,Name,Industry,Sub-Industry,Headquarters Location,Date added,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",3/4/1957,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",7/26/2017,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",3/4/1957,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/2012,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/2011,1989

In [75]:
#This code will provide the total rows & columns in the stockfinancial df.
stock_financials

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,1.387211e+11,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,1.078342e+10,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,1.021210e+11,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,1.813863e+11,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,9.876586e+10,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,70.24,30.94,1.170079,1.83,76.81,46.860,1.291502e+10,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,Yum! Brands Inc,Consumer Discretionary,76.30,27.25,1.797080,4.07,86.93,62.850,2.700330e+10,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,Zimmer Biomet Holdings,Health Care,115.53,14.32,0.794834,9.01,133.49,108.170,2.445470e+10,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,Zions Bancorp,Financials,50.71,17.73,1.480933,2.60,55.61,38.430,1.067068e+10,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,Zoetis,Health Care,71.51,32.80,0.682372,1.65,80.13,52.000,3.599111e+10,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [76]:
#This code will provide the total rows & columns in the stockinfo df.
stock_info

,Ticker,Name,Industry,Sub-Industry,Headquarters Location,Date added,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",3/4/1957,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",7/26/2017,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",3/4/1957,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/2012,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/2011,1989
...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",10/6/1997,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",12/23/2019,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",8/7/2001,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",6/22/2001,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",6/21/2013,1952

In [78]:
#Renaming the "Ticker" column to match the column name in the stocks_financials df
stock_info.rename(columns={"Ticker" : "Symbol"}, inplace="False")

#verifying that the name actually changed
stock_info.head()

,Symbol,Name,Industry,Sub-Industry,Headquarters Location,Date added,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",3/4/1957,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",7/26/2017,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",3/4/1957,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/2012,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/2011,1989

In [ ]:
stock_merged = pd.merge(stock_financials,stock_info,on=)